version: "3.9"

services:
  api:
    image: myapi:1.0  
    build: .
    container_name: myapi
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: myapi-sql
    restart: "no"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword!123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: